services:
  reverse-proxy:
    image: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      # So that Traefik can listen to Docker events
      - /var/run/docker.sock:/var/run/docker.sock
  attendance-manager:
    build: .
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    volumes:
      - ./dev.db:/app/dev.db
